from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
import datetime
import os


def export_to_pdf(text: str):
    filename = f"Travel_Itinerary_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    doc = SimpleDocTemplate(
        filename,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()
    story = []

    # -------------------------
    # Title
    # -------------------------
    story.append(
        Paragraph(
            "<b>AI Generated Travel Itinerary</b>",
            styles["Title"]
        )
    )
    story.append(Spacer(1, 12))

    story.append(
        Paragraph(
            f"<i>Generated on: {datetime.datetime.now().strftime('%d %B %Y')}</i>",
            styles["Normal"]
        )
    )
    story.append(Spacer(1, 20))

    # -------------------------
    # Main Itinerary Content
    # -------------------------
    for line in text.split("\n"):
        if line.strip().startswith("Day"):
            story.append(Spacer(1, 12))
            story.append(Paragraph(f"<b>{line}</b>", styles["Heading2"]))
        elif "TOTAL" in line.upper():
            story.append(Spacer(1, 15))
            story.append(
                Paragraph(
                    f"<b>{line}</b>",
                    styles["Heading2"]
                )
            )
        else:
            story.append(Paragraph(line, styles["Normal"]))

    story.append(Spacer(1, 25))

    # -------------------------
    # Footer
    # -------------------------
    story.append(
        Paragraph(
            "<i>Generated by Agentic AI Travel Planner</i>",
            styles["Normal"]
        )
    )

    doc.build(story)

    return filename
